CREATE TABLE workspace_calendar (
  workspace_id TEXT PRIMARY KEY REFERENCES workspace(id),
  version BIGINT NOT NULL CHECK(version > 0 AND version <= 9007199254740991),
  timezone TEXT
);
ALTER TABLE activity ADD COLUMN from_id TEXT;
ALTER TABLE activity ADD COLUMN to_id TEXT;
ALTER TABLE activity ADD COLUMN edge_type TEXT;
ALTER TABLE activity DROP CONSTRAINT activity_type_check;
ALTER TABLE activity ADD CONSTRAINT activity_type_check CHECK(type IN ('WORK_ITEM_CREATED','WORK_ITEM_UPDATED','WORK_ITEM_DELETED','WORK_ITEM_RESTORED','WORK_EDGE_ADDED','WORK_EDGE_REMOVED','WORKSPACE_SETTINGS_UPDATED'));
