ALTER TABLE activity DROP CONSTRAINT activity_type_check;
ALTER TABLE activity ADD CONSTRAINT activity_type_check CHECK(type IN ('RECURRENCE_TASK_CONVERTED','WORK_ITEM_CREATED','WORK_ITEM_UPDATED','WORK_ITEM_DELETED','WORK_ITEM_RESTORED','WORK_ITEM_PURGED','WORK_EDGE_ADDED','WORK_EDGE_REMOVED','WORKSPACE_SETTINGS_UPDATED'));
